Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'VIVOMEDIA.NeosUI.NodeReloadedOutOfBandEvent:NodeReloadedOutOfBandEvent':
            resource: resource://VIVOMEDIA.NeosUI.NodeReloadedOutOfBandEvent/Public/NodeReloadedOutOfBandEvent/Plugin.js
